language: node_js
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_6128db8e64b5_key -iv $encrypted_6128db8e64b5_iv
  -in id_rsa.enc -out id_rsa -d
