language: node_js
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
script:
- npm run test

before_install:
- openssl aes-256-cbc -K $encrypted_705dcafd9b79_key -iv $encrypted_705dcafd9b79_iv -in id_rsa.enc -out .travis/id_rsa -d
- chmod 600 .travis/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
after_script:
- scp -o StrictHostKeyChecking=no app.js root@180.76.244.108:/home/conmunication


