language: node_js
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
script:
- npm run test

before_install:
- openssl aes-256-cbc -K $encrypted_6128db8e64b5_key -iv $encrypted_6128db8e64b5_iv

- in .travis/id_rsa.enc -out id_rsa -d

- mv id_rsa ~/.ssh -f

- chmod 600 ~/.ssh/id_rsa

- eval $(ssh-agent)

- ssh-add ~/.ssh/id_rsa

- cp .travis/ssh_config ~/.ssh/config

after_script:

- scp -o StrictHostKeyChecking=no app.js root@180.76.244.108:/home/conmunication


